
label define healthlabels 1 "Poor" 2 "Fair" 3 "Good" 4 "Very good" 5 "Excellent"
label values health healthlabels

label define incomelabels 4 "Under £8,000" 10 "£8,000 -- £11,999" 14 "£12,000 -- £15,999" 18 "£16,000 -- £19,999" 22 "£20,000 -- £23,999" 28 "£24,000 -- £31,999" 36 "£32,000 -- £39,999" 48 "£40,000 -- £55,999" 64 "£56,000 -- £71,999" 84 "£72,000 -- £95,999" 108 "£96,000 or more"
label values hhinc incomelabels

label variable lctout_marine    "Marine and coastal margins" 
label variable lctout_watery    "Freshwater, wetlands and flood plains" 
label variable lctout_mountain  "Mountains, moors and heathland" 
label variable lctout_grassy    "Semi-natural grasslands" 
label variable lctout_farmland  "Enclosed farmland" 
label variable lctout_conifers  "Coniferous woodland" 
label variable lctout_allwoods  "Woodland"
label variable lctout_woody     "Broad-leaved/mixed woodland" 
label variable lctout_bare      "Inland bare ground" 
label variable lctout_suburb    "Suburban/rural developed" 
label variable b_lctout_conturb "Continuous urban" 

label variable with_partner     "Spouse, partner, girl/boyfriend" 
label variable with_child       "Children" 
label variable with_relative    "Other family members" 
label variable with_peers       "Colleagues, classmates" 
label variable with_client      "Clients, customers" 
label variable with_friend      "Friends" 
label variable with_other       "Other people participant knows" 

label variable at_home          "At home"
label variable at_work          "At work" 
label variable elsewhere        "Elsewhere"
 
label variable indoors          "Indoors" 
label variable vehicle          "In a vehicle" 
label variable outdoors         "Outdoors" 

label variable is_daylight_out  "Daylight" 
label variable sunny_out        "Sunny" 
label variable rain_out         "Rainy" 
label variable snow_out         "Snowy" 
label variable fog_out          "Foggy" 

label variable b_temp_0_out     "< 0 degC" 
label variable temp_8_out       "0 – 7 degC" 
label variable temp_16_out      "8 – 15 degC" 
label variable temp_24_out      "16 – 23 degC" 
label variable temp_hi_out      "24+ degC" 

label variable b_wind_5_out     "0 - 4 km/h" 
label variable wind_15_out      "5 - 14 km/h" 
label variable wind_25_out      "15 - 24 km/h" 
label variable wind_hi_out      "25+ km/h" 

label variable do_work "Working, studying"
label variable do_meet "In a meeting, seminar, class"
label variable do_travel "Travelling, commuting"
label variable do_cook "Cooking, preparing food"
label variable do_chores "Housework, chores, DIY"
label variable do_admin "Admin, finances, organising"
label variable do_shop "Shopping, errands"
label variable do_wait "Waiting, queueing"
label variable do_child "Childcare, playing with children"
label variable do_pet "Pet care, playing with pets"
label variable do_care "Care or help for adults"
label variable do_rest "Sleeping, resting, relaxing"
label variable do_sick "Sick in bed"
label variable do_pray "Meditating, religious activities"
label variable do_wash "Washing, dressing, grooming"
label variable do_love "Intimacy, making love"
label variable do_chat "Talking, chatting, socialising"
label variable do_eat "Eating, snacking"
label variable do_caffeine "Drinking tea/coffee"
label variable do_booze "Drinking alcohol"
label variable do_smoke "Smoking"
label variable do_msg "Texting, email, social media"
label variable do_net "Browsing the Internet"
label variable do_tv "Watching TV, film"
label variable do_music "Listening to music"
label variable do_speech "Listening to speech/podcast"
label variable do_read "Reading"
label variable do_theatre "Theatre, dance, concert"
label variable do_museum "Exhibition, museum, library"
label variable do_match "Match, sporting event"
label variable do_walk "Walking, hiking"
label variable do_sport "Sports, running, exercise"
label variable do_gardening "Gardening, allotment"
label variable do_birdwatch "Birdwatching, nature watching"
label variable do_hunt "Hunting, fishing"
label variable do_compgame "Computer games, iPhone games"
label variable do_game "Other games, puzzles"
label variable do_bet "Gambling, betting"
label variable do_art "Hobbies, arts, crafts"
label variable do_sing "Singing, performing"
label variable do_other "Something else (version < 1.0.2)"
label variable do_other2 "Something else (version >= 1.0.2)"