
-- London (

drop view if exists london_export;
create view london_export as (
  select 
    s.id,
    
    s.home_postcode,
    s.home_lat,
    s.home_lon,
    s.home_zoom,
    s.home_is_valid,
    s.home_is_approx,
    s.other_postcode,
    s.other_lat,
    s.other_lon,
    s.other_zoom,
    s.other_is_valid,
    s.other_is_approx,
    s.home_lsoa_or_dzone,
    s.other_lsoa_or_dzone,
    s.home_lsoa_area,
    s.other_lsoa_area,
    s.home_lhr09_leq,
    s.other_lhr09_leq,
    s.home_noise_rail_lden,
    s.other_noise_rail_lden,
    s.home_noise_road_lden,
    s.other_noise_road_lden,
    s.home_aod,
    s.other_aod,
    s.home_lsoa_house_price_fe,
    s.other_lsoa_house_price_fe,
    s.home_house_price_med9,
    s.home_popdens_ppkm2,
    s.other_popdens_ppkm2,
    
    c.home_tno,
    c.home_vap,
    c.home_rb,
    c.other_tno,
    c.other_vap,
    c.other_rb,
    
    e.home_lsoa_hh_count,
    e.home_lsoa_medhhinc,
    e.home_lsoa_pop,
    e.other_lsoa_hh_count,
    e.other_lsoa_medhhinc,
    e.other_lsoa_pop,
    
    l.home_map_no2a,
    l.home_map_pm10a,
    l.home_map_pm10e,
    l.other_map_no2a,
    l.other_map_pm10a,
    l.other_map_pm10e,
    l.home_pcc_no2a,
    l.home_pcc_pm10a,
    l.home_pcc_pm10e,
    
    n.home_coast_sd200,
    n.home_coast_sd1000,
    n.home_water_sd200,
    n.home_water_sd1000,
    n.home_mountain_sd200,
    n.home_mountain_sd1000,
    n.home_grassland_sd200,
    n.home_grassland_sd1000,
    n.home_farmland_sd200,
    n.home_farmland_sd1000,
    n.home_woodland_sd200,
    n.home_woodland_sd1000,
    n.home_suburban_sd200,
    n.home_suburban_sd1000,
    n.home_inlandbare_sd200,
    n.home_inlandbare_sd1000,
    n.other_coast_sd200,
    n.other_coast_sd1000,
    n.other_water_sd200,
    n.other_water_sd1000,
    n.other_mountain_sd200,
    n.other_mountain_sd1000,
    n.other_grassland_sd200,
    n.other_grassland_sd1000,
    n.other_farmland_sd200,
    n.other_farmland_sd1000,
    n.other_woodland_sd200,
    n.other_woodland_sd1000,
    n.other_suburban_sd200,
    n.other_suburban_sd1000,
    n.other_inlandbare_sd200,
    n.other_inlandbare_sd1000,
    
    u.home_coast_r200,
    u.home_coast_r1000,
    u.home_coast_r3000,
    u.home_water_r200,
    u.home_water_r1000,
    u.home_water_r3000,
    u.home_mountain_r200,
    u.home_mountain_r1000,
    u.home_mountain_r3000,
    u.home_grassland_r200,
    u.home_grassland_r1000,
    u.home_grassland_r3000,
    u.home_farmland_r200,
    u.home_farmland_r1000,
    u.home_farmland_r3000,
    u.home_woodland_r200,
    u.home_woodland_r1000,
    u.home_woodland_r3000,
    u.home_suburban_r200,
    u.home_suburban_r1000,
    u.home_suburban_r3000,
    u.home_inlandbare_r200,
    u.home_inlandbare_r1000,
    u.home_inlandbare_r3000,
    u.other_coast_r200,
    u.other_coast_r1000,
    u.other_coast_r3000,
    u.other_water_r200,
    u.other_water_r1000,
    u.other_water_r3000,
    u.other_mountain_r200,
    u.other_mountain_r1000,
    u.other_mountain_r3000,
    u.other_grassland_r200,
    u.other_grassland_r1000,
    u.other_grassland_r3000,
    u.other_farmland_r200,
    u.other_farmland_r1000,
    u.other_farmland_r3000,
    u.other_woodland_r200,
    u.other_woodland_r1000,
    u.other_woodland_r3000,
    u.other_suburban_r200,
    u.other_suburban_r1000,
    u.other_suburban_r3000,
    u.other_inlandbare_r200,
    u.other_inlandbare_r1000,
    u.other_inlandbare_r3000,
    u.home_coast_r10000,
    u.home_water_r10000,
    u.home_mountain_r10000,
    u.home_grassland_r10000,
    u.home_farmland_r10000,
    u.home_woodland_r10000,
    u.home_suburban_r10000,
    u.home_inlandbare_r10000,
    u.other_coast_r10000,
    u.other_water_r10000,
    u.other_mountain_r10000,
    u.other_grassland_r10000,
    u.other_farmland_r10000,
    u.other_woodland_r10000,
    u.other_suburban_r10000,
    u.other_inlandbare_r10000,
    
    p.home_coast_lsoaprop,
    p.home_water_lsoaprop,
    p.home_mountain_lsoaprop,
    p.home_grassland_lsoaprop,
    p.home_farmland_lsoaprop,
    p.home_woodland_lsoaprop,
    p.home_suburban_lsoaprop,
    p.home_inlandbare_lsoaprop,
    p.other_coast_lsoaprop,
    p.other_water_lsoaprop,
    p.other_mountain_lsoaprop,
    p.other_grassland_lsoaprop,
    p.other_farmland_lsoaprop,
    p.other_woodland_lsoaprop,
    p.other_suburban_lsoaprop,
    p.other_inlandbare_lsoaprop,
    
    g.home_osm_green_sd200,
    g.home_osm_green_sd1000,
    g.home_osm_park_sd200,
    g.home_osm_park_sd1000,
    g.home_gigl_green_sd200,
    g.home_gigl_green_sd1000,
    g.other_osm_green_sd200,
    g.other_osm_green_sd1000,
    g.other_osm_park_sd200,
    g.other_osm_park_sd1000,
    g.other_gigl_green_sd200,
    g.other_gigl_green_sd1000,
    
    h.home_osm_green_r200,
    h.home_osm_green_r1000,
    h.home_osm_green_r3000,
    h.home_osm_park_r200,
    h.home_osm_park_r1000,
    h.home_osm_park_r3000,
    h.home_gigl_green_r200,
    h.home_gigl_green_r1000,
    h.home_gigl_green_r3000,
    h.other_osm_green_r200,
    h.other_osm_green_r1000,
    h.other_osm_green_r3000,
    h.other_osm_park_r200,
    h.other_osm_park_r1000,
    h.other_osm_park_r3000,
    h.other_gigl_green_r200,
    h.other_gigl_green_r1000,
    h.other_gigl_green_r3000,
    
    d.home_map_centroid_distance,
    d.home_map_poly_distance,
    d.other_map_centroid_distance,
    d.other_map_poly_distance,
    
    m.home_z1_dist,
    m.home_z1tube_dist,
    m.home_tube_dist,
    m.home_mway_dist,
    m.home_railway_dist,
    m.home_station_dist,
    m.home_coast_dist,
    m.home_river_dist,
    m.other_z1_dist,
    m.other_z1tube_dist,
    m.other_tube_dist,
    m.other_mway_dist,
    m.other_railway_dist,
    m.other_station_dist,
    m.other_coast_dist,
    m.other_river_dist
    
  from london_survey s
  left join london_crime                c on s.id = c.id
  left join london_experian2010         e on s.id = e.id
  left join london_laei2008             l on s.id = l.id
  left join london_lcm_normal           n on s.id = n.id
  left join london_lcm_uniform          u on s.id = u.id
  left join london_lcm_by_lsoa          p on s.id = p.id
  left join london_green_normal         g on s.id = g.id
  left join london_green_uniform        h on s.id = h.id
  left join london_location_derivatives d on s.id = d.id
  left join london_meridian             m on s.id = m.id
);

)

-- UK (

drop view if exists uk_export;
create view uk_export as (
  select 
    s.id,
    
    s.home_postcode,
    s.other_postcode,
    s.home_lsoa_or_dzone,
    s.other_lsoa_or_dzone,
    s.home_ttwa,
    s.other_ttwa,
    s.home_lsoa_area,
    s.other_lsoa_area,
    s.home_lsoa_house_price_fe,
    s.other_lsoa_house_price_fe,
    s.home_house_price_med9,
    s.home_popdens_ppkm2,
    s.other_popdens_ppkm2,
    s.home_country,
    s.other_country,
    
    e.home_lsoa_hh_count,
    e.home_lsoa_medhhinc,
    e.home_lsoa_pop,
    e.other_lsoa_hh_count,
    e.other_lsoa_medhhinc,
    e.other_lsoa_pop,
    
    n.home_coast_sd200,
    n.home_coast_sd1000,
    n.home_water_sd200,
    n.home_water_sd1000,
    n.home_mountain_sd200,
    n.home_mountain_sd1000,
    n.home_grassland_sd200,
    n.home_grassland_sd1000,
    n.home_farmland_sd200,
    n.home_farmland_sd1000,
    n.home_woodland_sd200,
    n.home_woodland_sd1000,
    n.home_suburban_sd200,
    n.home_suburban_sd1000,
    n.home_inlandbare_sd200,
    n.home_inlandbare_sd1000,
    n.other_coast_sd200,
    n.other_coast_sd1000,
    n.other_water_sd200,
    n.other_water_sd1000,
    n.other_mountain_sd200,
    n.other_mountain_sd1000,
    n.other_grassland_sd200,
    n.other_grassland_sd1000,
    n.other_farmland_sd200,
    n.other_farmland_sd1000,
    n.other_woodland_sd200,
    n.other_woodland_sd1000,
    n.other_suburban_sd200,
    n.other_suburban_sd1000,
    n.other_inlandbare_sd200,
    n.other_inlandbare_sd1000,
    
    u.home_coast_r200,
    u.home_coast_r1000,
    u.home_coast_r3000,
    u.home_water_r200,
    u.home_water_r1000,
    u.home_water_r3000,
    u.home_mountain_r200,
    u.home_mountain_r1000,
    u.home_mountain_r3000,
    u.home_grassland_r200,
    u.home_grassland_r1000,
    u.home_grassland_r3000,
    u.home_farmland_r200,
    u.home_farmland_r1000,
    u.home_farmland_r3000,
    u.home_woodland_r200,
    u.home_woodland_r1000,
    u.home_woodland_r3000,
    u.home_suburban_r200,
    u.home_suburban_r1000,
    u.home_suburban_r3000,
    u.home_inlandbare_r200,
    u.home_inlandbare_r1000,
    u.home_inlandbare_r3000,
    u.other_coast_r200,
    u.other_coast_r1000,
    u.other_coast_r3000,
    u.other_water_r200,
    u.other_water_r1000,
    u.other_water_r3000,
    u.other_mountain_r200,
    u.other_mountain_r1000,
    u.other_mountain_r3000,
    u.other_grassland_r200,
    u.other_grassland_r1000,
    u.other_grassland_r3000,
    u.other_farmland_r200,
    u.other_farmland_r1000,
    u.other_farmland_r3000,
    u.other_woodland_r200,
    u.other_woodland_r1000,
    u.other_woodland_r3000,
    u.other_suburban_r200,
    u.other_suburban_r1000,
    u.other_suburban_r3000,
    u.other_inlandbare_r200,
    u.other_inlandbare_r1000,
    u.other_inlandbare_r3000,
    u.home_coast_r10000,
    u.home_water_r10000,
    u.home_mountain_r10000,
    u.home_grassland_r10000,
    u.home_farmland_r10000,
    u.home_woodland_r10000,
    u.home_suburban_r10000,
    u.home_inlandbare_r10000,
    u.other_coast_r10000,
    u.other_water_r10000,
    u.other_mountain_r10000,
    u.other_grassland_r10000,
    u.other_farmland_r10000,
    u.other_woodland_r10000,
    u.other_suburban_r10000,
    u.other_inlandbare_r10000,
    
    p.home_coast_lsoaprop,
    p.home_water_lsoaprop,
    p.home_mountain_lsoaprop,
    p.home_grassland_lsoaprop,
    p.home_farmland_lsoaprop,
    p.home_woodland_lsoaprop,
    p.home_suburban_lsoaprop,
    p.home_inlandbare_lsoaprop,
    p.other_coast_lsoaprop,
    p.other_water_lsoaprop,
    p.other_mountain_lsoaprop,
    p.other_grassland_lsoaprop,
    p.other_farmland_lsoaprop,
    p.other_woodland_lsoaprop,
    p.other_suburban_lsoaprop,
    p.other_inlandbare_lsoaprop,

    m.home_mway_dist,
    m.home_aroad_dist,
    m.home_railway_dist,
    m.home_station_dist,
    m.home_coast_dist,
    m.home_river_dist,
    m.home_natpark_dist,
    m.home_aonb_dist,
    m.home_nnr_dist,
    m.other_mway_dist,
    m.other_aroad_dist,
    m.other_railway_dist,
    m.other_station_dist,
    m.other_coast_dist,
    m.other_river_dist,
    m.other_natpark_dist,
    m.other_aonb_dist,
    m.other_nnr_dist
    
  from uk_survey s
  left join uk_experian2010         e on s.id = e.id
  left join uk_lcm_normal           n on s.id = n.id
  left join uk_lcm_uniform          u on s.id = u.id
  left join uk_lcm_by_lsoa          p on s.id = p.id
  left join uk_nearests             m on s.id = m.id
);

)

select * from london_export; -- save from pgAdmin
select * from uk_export;

