
create view london_export as (
  select 
    s.id,
    
    s.home_postcode,
    s.home_lat,
    s.home_lon,
    s.home_zoom,
    s.home_is_valid,
    s.home_is_approx,
    s.other_postcode,
    s.other_lat,
    s.other_lon,
    s.other_zoom,
    s.other_is_valid,
    s.other_is_approx,
    s.home_lsoa_or_dzone,
    s.other_lsoa_or_dzone,
    s.home_lsoa_area,
    s.other_lsoa_area,
    s.home_lhr09_leq,
    s.other_lhr09_leq,
    s.home_noise_rail_lden,
    s.other_noise_rail_lden,
    s.home_noise_road_lden,
    s.other_noise_road_lden,
    s.home_aod,
    s.other_aod,
    s.home_lsoa_house_price_fe,
    s.other_lsoa_house_price_fe,
    
    c.home_tno,
    c.home_vap,
    c.home_rb,
    c.other_tno,
    c.other_vap,
    c.other_rb,
    
    e.home_lsoa_hh_count,
    e.home_lsoa_medhhinc,
    e.home_lsoa_pop,
    e.other_lsoa_hh_count,
    e.other_lsoa_medhhinc,
    e.other_lsoa_pop,
    
    l.home_map_no2a,
    l.home_map_pm10a,
    l.home_map_pm10e,
    l.other_map_no2a,
    l.other_map_pm10a,
    l.other_map_pm10e,
    l.home_pcc_no2a,
    l.home_pcc_pm10a,
    l.home_pcc_pm10e,
    
    n.home_coast_sd200,
    n.home_coast_sd1000,
    n.home_water_sd200,
    n.home_water_sd1000,
    n.home_mountain_sd200,
    n.home_mountain_sd1000,
    n.home_grassland_sd200,
    n.home_grassland_sd1000,
    n.home_farmland_sd200,
    n.home_farmland_sd1000,
    n.home_woodland_sd200,
    n.home_woodland_sd1000,
    n.home_suburban_sd200,
    n.home_suburban_sd1000,
    n.home_inlandbare_sd200,
    n.home_inlandbare_sd1000,
    n.other_coast_sd200,
    n.other_coast_sd1000,
    n.other_water_sd200,
    n.other_water_sd1000,
    n.other_mountain_sd200,
    n.other_mountain_sd1000,
    n.other_grassland_sd200,
    n.other_grassland_sd1000,
    n.other_farmland_sd200,
    n.other_farmland_sd1000,
    n.other_woodland_sd200,
    n.other_woodland_sd1000,
    n.other_suburban_sd200,
    n.other_suburban_sd1000,
    n.other_inlandbare_sd200,
    n.other_inlandbare_sd1000,
    
    -- lcm uniform
    
    d.home_map_centroid_distance,
    d.home_map_poly_distance,
    d.other_map_centroid_distance,
    d.other_map_poly_distance,
    
    m.home_z1tube_dist,
    m.home_tube_dist,
    m.home_mway_dist,
    m.home_railway_dist,
    m.home_station_dist,
    m.home_coast_dist,
    m.home_river_dist,
    m.other_z1tube_dist,
    m.other_tube_dist,
    m.other_mway_dist,
    m.other_railway_dist,
    m.other_station_dist,
    m.other_coast_dist,
    m.other_river_dist,
    
  from london_survey s
  left join london_crime                c on s.id = c.id
  left join london_experian             e on s.id = e.id
  left join london_laei2008             l on s.id = l.id
  left join london_lcm_normal           n on s.id = n.id
  left join london_location_derivatives d on s.id = d.id
  left join london_meridian             m on s.id = m.id
  
);